---
title: "Clase 3 - Actividad"
output: html_document
---

```{r setup, include=FALSE}
library(nycflights13)
library(tidyverse)
ls("package:nycflights13")
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
glimpse(weather)
weather <- weather
weather$origin <- as.factor(weather$origin)
weather$wind_dir <- as.factor(weather$wind_dir)
weather <- weather %>% drop_na(wind_dir)
```

## Including Plots

You can also embed plots, for example:


```{r}
g <- ggplot(weather, aes(x = temp,y=..density..))
g + geom_histogram(col = 'white',
                   fill="#B06EF5", 
                   size=0.1) +  # change binwidth
  labs(title="Histogram") 
```

```{r}
ggplot(weather, aes(x = temp,y=..density.. , fill = factor(month))) + 
  geom_histogram(alpha = 0.8, color = 'white')
```

```{r}
ggplot(weather, aes(x = factor(month), y = humid, color = factor(month))) + 
  geom_boxplot() + 
  theme(legend.position = 'none')
```



```{r}
ggplot(weather, aes(x = wind_dir, fill  = factor(month))) + 
  geom_bar() + 
  coord_polar(theta = "x")
```

```{r}
g <- ggplot(weather, aes(factor(month), humid))
g + geom_boxplot(aes(fill=factor(month))) +  
  scale_fill_brewer(palette = "Spectral") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) +
  labs(title="Monthly Humidity",
       subtitle="Box-plots",
       x="Month",
       y="Relative humidity")
```

